<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Fashion Store - Product List</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
   
  
</head>
<body id="main-body">
    <div class="main-container">
        <?php echo $this->getChildHtml('filter'); ?>
        <?php echo $this->getChildHtml('products'); ?>
    </div>
</body>
</html>