<?php 

?>

<h1>new</h1>
<div class="main-part">
    <form action="<?php echo $this->getUrl('*/*/save'); ?>" method="POST">
        <div class="section">
            <input type="hidden" name="events[event_id]" value="<?php echo $this->getEvent()->getEventId() ?>" />
        </div>

        <div class="section">
            <label for="events[title]">Title</label>
            <input type="text" name="events[title]" value="<?php echo $this->getEvent()->getTitle() ?>" />
        </div>

        <div class="section">
            <label for="events[description]">Description</label>
            <input type="text" name="events[description]" value="<?php echo $this->getEvent()->getDescription() ?>" />
        </div>

        <div class="section">
            <label for="events[date]">Date</label>
            <input type="date" name="events[date]" value="<?php echo $this->getEvent()->getDate() ?>" />
        </div>

        <div class="section">
            <label for="events[location]">Location</label>
            <input type="text" name="events[location]" value="<?php echo $this->getEvent()->getLocation()  ?>" />
        </div>

        <div class="section">
            <label for="events[capacity]">Capacity</label>
            <input type="number" name="events[capacity]" value="<?php  echo $this->getEvent()->getCapacity() ?>" />
        </div>

        <button type="submit">Submit</button>
    </form>
</div>