<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>
        @import url('https://fonts.googleapis.com/css?family=Open+Sans');
/* 
* {
    box-sizing: border-box;
    margin: 0;
    padding: 0;
}

body {
    font-family: 'Open Sans', sans-serif;
    height: 100vh;
} */

.button {
    background-color: #fff;
    border: 0;
    color: #aaa;
    cursor: pointer;
    font-size: 16px;
    padding: 15px;
    transition: color .2s ease-in;
}

.button:hover {
    color: #222;
}

.button:focus {
    outline: 0;
}

.slider-container {
    position: relative;
    overflow: hidden;
    width: 100vw;
    height: 100vh;
}

.left-slide {
    height: 100%;
    position: absolute;
    top: 0;
    left: 0;
    width: 35%;
    transition: transform .5s ease-in-out;
}

.left-slide > div {
    align-items: center;
    color: #fff;
    display: flex;
    flex-direction: column;
    justify-content: center;
    height: 100%;
    width: 100%;
}

.left-slide h1 {
    font-size: 40px;
    margin-bottom: 10px;
    margin-top: -30px;
}

.right-slide {
    height: 100%;
    position: absolute;
    top: 0;
    left: 35%;
    width: 65%;
    transition: transform .5s ease-in-out;
}

.right-slide > div{
    background-repeat: no-repeat;
    background-size: cover;
    background-position: center center;
    height: 100%;
    width: 100%;
}

.slider-container .action-buttons button {
    position: absolute;
    left: 35%;
    top: 50%;
    z-index: 100;
}

.slider-container .action-buttons .down-button {
    border-top-left-radius: 5px;
    border-bottom-left-radius: 5px;
    transform: translateX(-100%);
}

.slider-container .action-buttons .up-button {
    border-top-right-radius: 5px;
    border-bottom-right-radius: 5px;
    transform: translateY(-100%);
}

footer {
    bottom: 0;
    background-color: #222;
	color: #fff;
	font-family: 'Open Sans', 'Arial', sans-serif;
	padding: 10px;
	position: fixed;
	left: 0;
	right: 0;
	letter-spacing: 1px;
	text-align: center;
}

footer i {
	color: red;
}

footer a {
	color: #3C97BF;
	text-decoration: none;
}
    </style>
</head>
<body>
    


<div class="slider-container">
	<div class="left-slide">
		<div style="background-color: #FD3555">
			<h1>Nature flower</h1>
			<p>all in pink</p>
		</div>
		<div style="background-color: #2A86BA">
			<h1>Bluuue Sky</h1>
			<p>with it's mountains</p>
		</div>
		<div style="background-color: #252E33">
			<h1>Lonely castle</h1>
			<p>in the wilderness</p>
		</div>
		<div style="background-color: #FFB866">
			<h1>Flying eagle</h1>
			<p>in the sunset</p>
		</div>
	</div>
	<div class="right-slide">
		<div style="background-image: url('https://images.unsplash.com/photo-1508768787810-6adc1f613514?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=e27f6661df21ed17ab5355b28af8df4e&auto=format&fit=crop&w=1350&q=80')"></div>
		<div style="background-image: url('https://images.unsplash.com/photo-1519981593452-666cf05569a9?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=90ed8055f06493290dad8da9584a13f7&auto=format&fit=crop&w=715&q=80')"></div>
		<div style="background-image: url('https://images.unsplash.com/photo-1486899430790-61dbf6f6d98b?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=8ecdee5d1b3ed78ff16053b0227874a2&auto=format&fit=crop&w=1002&q=80')"></div>
		<div style="background-image: url('https://images.unsplash.com/photo-1510942201312-84e7962f6dbb?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=da4ca7a78004349f1b63f257e50e4360&auto=format&fit=crop&w=1050&q=80')"></div>
	</div>

	<div class="action-buttons">
		<button class="button down-button" >
            <i class="fa fa-arrow-down" aria-hidden="true"></i>
		</button>
		<button class="button up-button">
			<i class="fa fa-arrow-up"></i>
		</button>
	</div>
</div>
<!-- 
<footer>
	<p>
		Created with <i class="fa fa-heart"></i> by 
		<a target="_blank" href="http://florin-pop.com">Florin Pop</a>
		- More on
		<a target="_blank" href="https://github.com/florinpop17/work-journal">Github</a>
		- Inspired from
		<a target="_blank" href="https://codepen.io/GrandvincentMarion/full/NaEELP">Codepen</a>
	</p>
</footer>  -->

<script>
    const sliderContainer = document.querySelector('.slider-container');
const slideRight = document.querySelector('.right-slide');
const slideLeft = document.querySelector('.left-slide');
const upButton = document.querySelector('.up-button');
const downButton = document.querySelector('.down-button');
const slidesLength = slideRight.querySelectorAll('div').length;

let activeSlideIndex = 0;

slideLeft.style.top = `-${(slidesLength - 1) * 100}vh`;

upButton.addEventListener('click', () => changeSlide('up'));
downButton.addEventListener('click', () => changeSlide('down'));

const changeSlide = (direction) => {
    const sliderHeight = sliderContainer.clientHeight;
    if(direction === 'up') {
        activeSlideIndex++;
        if(activeSlideIndex > slidesLength - 1) {
            activeSlideIndex = 0;
        }
    } else if (direction === 'down') {
        activeSlideIndex--;
        if(activeSlideIndex < 0) {
            activeSlideIndex = slidesLength - 1;
        }
    }
    slideRight.style.transform = `translateY(-${activeSlideIndex * sliderHeight}px)`;
    slideLeft.style.transform = `translateY(${activeSlideIndex * sliderHeight}px)`;
}
</script>
</body>
</html>